### PR TITLE
Added travis

### PR DESCRIPTION
**Pull request by zopa-simon-cass**
Added Travis - used this guide https://medium.com/full-taxx/how-to-setup-travis-ci-for-a-rails-application-78a453963300

### CODE REVIEW

**Comment by GabMat97** [comment]
Looks good to me!

**Review by Sindex42 — APPROVED** [review]
Looks good, travis passing

**Comment by anhuiyang** [comment]
travis passing:)

**Review by anhuiyang — APPROVED** [review]
travis passing:D

**Pull request merged**
